// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/inspire-manager/pkg/db/ent/couponspecialoffer"
	"github.com/NpoolPlatform/inspire-manager/pkg/db/ent/predicate"
)

// CouponSpecialOfferDelete is the builder for deleting a CouponSpecialOffer entity.
type CouponSpecialOfferDelete struct {
	config
	hooks    []Hook
	mutation *CouponSpecialOfferMutation
}

// Where appends a list predicates to the CouponSpecialOfferDelete builder.
func (csod *CouponSpecialOfferDelete) Where(ps ...predicate.CouponSpecialOffer) *CouponSpecialOfferDelete {
	csod.mutation.Where(ps...)
	return csod
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (csod *CouponSpecialOfferDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(csod.hooks) == 0 {
		affected, err = csod.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CouponSpecialOfferMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			csod.mutation = mutation
			affected, err = csod.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(csod.hooks) - 1; i >= 0; i-- {
			if csod.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = csod.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, csod.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (csod *CouponSpecialOfferDelete) ExecX(ctx context.Context) int {
	n, err := csod.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (csod *CouponSpecialOfferDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: couponspecialoffer.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: couponspecialoffer.FieldID,
			},
		},
	}
	if ps := csod.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, csod.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// CouponSpecialOfferDeleteOne is the builder for deleting a single CouponSpecialOffer entity.
type CouponSpecialOfferDeleteOne struct {
	csod *CouponSpecialOfferDelete
}

// Exec executes the deletion query.
func (csodo *CouponSpecialOfferDeleteOne) Exec(ctx context.Context) error {
	n, err := csodo.csod.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{couponspecialoffer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (csodo *CouponSpecialOfferDeleteOne) ExecX(ctx context.Context) {
	csodo.csod.ExecX(ctx)
}
