// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/inspire-manager/pkg/db/ent/orderpercent"
	"github.com/NpoolPlatform/inspire-manager/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// OrderPercentQuery is the builder for querying OrderPercent entities.
type OrderPercentQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.OrderPercent
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrderPercentQuery builder.
func (opq *OrderPercentQuery) Where(ps ...predicate.OrderPercent) *OrderPercentQuery {
	opq.predicates = append(opq.predicates, ps...)
	return opq
}

// Limit adds a limit step to the query.
func (opq *OrderPercentQuery) Limit(limit int) *OrderPercentQuery {
	opq.limit = &limit
	return opq
}

// Offset adds an offset step to the query.
func (opq *OrderPercentQuery) Offset(offset int) *OrderPercentQuery {
	opq.offset = &offset
	return opq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (opq *OrderPercentQuery) Unique(unique bool) *OrderPercentQuery {
	opq.unique = &unique
	return opq
}

// Order adds an order step to the query.
func (opq *OrderPercentQuery) Order(o ...OrderFunc) *OrderPercentQuery {
	opq.order = append(opq.order, o...)
	return opq
}

// First returns the first OrderPercent entity from the query.
// Returns a *NotFoundError when no OrderPercent was found.
func (opq *OrderPercentQuery) First(ctx context.Context) (*OrderPercent, error) {
	nodes, err := opq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{orderpercent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (opq *OrderPercentQuery) FirstX(ctx context.Context) *OrderPercent {
	node, err := opq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrderPercent ID from the query.
// Returns a *NotFoundError when no OrderPercent ID was found.
func (opq *OrderPercentQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = opq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{orderpercent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (opq *OrderPercentQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := opq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrderPercent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrderPercent entity is found.
// Returns a *NotFoundError when no OrderPercent entities are found.
func (opq *OrderPercentQuery) Only(ctx context.Context) (*OrderPercent, error) {
	nodes, err := opq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{orderpercent.Label}
	default:
		return nil, &NotSingularError{orderpercent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (opq *OrderPercentQuery) OnlyX(ctx context.Context) *OrderPercent {
	node, err := opq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrderPercent ID in the query.
// Returns a *NotSingularError when more than one OrderPercent ID is found.
// Returns a *NotFoundError when no entities are found.
func (opq *OrderPercentQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = opq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{orderpercent.Label}
	default:
		err = &NotSingularError{orderpercent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (opq *OrderPercentQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := opq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrderPercents.
func (opq *OrderPercentQuery) All(ctx context.Context) ([]*OrderPercent, error) {
	if err := opq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return opq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (opq *OrderPercentQuery) AllX(ctx context.Context) []*OrderPercent {
	nodes, err := opq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrderPercent IDs.
func (opq *OrderPercentQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := opq.Select(orderpercent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (opq *OrderPercentQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := opq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (opq *OrderPercentQuery) Count(ctx context.Context) (int, error) {
	if err := opq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return opq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (opq *OrderPercentQuery) CountX(ctx context.Context) int {
	count, err := opq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (opq *OrderPercentQuery) Exist(ctx context.Context) (bool, error) {
	if err := opq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return opq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (opq *OrderPercentQuery) ExistX(ctx context.Context) bool {
	exist, err := opq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrderPercentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (opq *OrderPercentQuery) Clone() *OrderPercentQuery {
	if opq == nil {
		return nil
	}
	return &OrderPercentQuery{
		config:     opq.config,
		limit:      opq.limit,
		offset:     opq.offset,
		order:      append([]OrderFunc{}, opq.order...),
		predicates: append([]predicate.OrderPercent{}, opq.predicates...),
		// clone intermediate query.
		sql:    opq.sql.Clone(),
		path:   opq.path,
		unique: opq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrderPercent.Query().
//		GroupBy(orderpercent.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (opq *OrderPercentQuery) GroupBy(field string, fields ...string) *OrderPercentGroupBy {
	grbuild := &OrderPercentGroupBy{config: opq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := opq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return opq.sqlQuery(ctx), nil
	}
	grbuild.label = orderpercent.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.OrderPercent.Query().
//		Select(orderpercent.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (opq *OrderPercentQuery) Select(fields ...string) *OrderPercentSelect {
	opq.fields = append(opq.fields, fields...)
	selbuild := &OrderPercentSelect{OrderPercentQuery: opq}
	selbuild.label = orderpercent.Label
	selbuild.flds, selbuild.scan = &opq.fields, selbuild.Scan
	return selbuild
}

func (opq *OrderPercentQuery) prepareQuery(ctx context.Context) error {
	for _, f := range opq.fields {
		if !orderpercent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if opq.path != nil {
		prev, err := opq.path(ctx)
		if err != nil {
			return err
		}
		opq.sql = prev
	}
	if orderpercent.Policy == nil {
		return errors.New("ent: uninitialized orderpercent.Policy (forgotten import ent/runtime?)")
	}
	if err := orderpercent.Policy.EvalQuery(ctx, opq); err != nil {
		return err
	}
	return nil
}

func (opq *OrderPercentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrderPercent, error) {
	var (
		nodes = []*OrderPercent{}
		_spec = opq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*OrderPercent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &OrderPercent{config: opq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(opq.modifiers) > 0 {
		_spec.Modifiers = opq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, opq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (opq *OrderPercentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := opq.querySpec()
	if len(opq.modifiers) > 0 {
		_spec.Modifiers = opq.modifiers
	}
	_spec.Node.Columns = opq.fields
	if len(opq.fields) > 0 {
		_spec.Unique = opq.unique != nil && *opq.unique
	}
	return sqlgraph.CountNodes(ctx, opq.driver, _spec)
}

func (opq *OrderPercentQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := opq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (opq *OrderPercentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   orderpercent.Table,
			Columns: orderpercent.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: orderpercent.FieldID,
			},
		},
		From:   opq.sql,
		Unique: true,
	}
	if unique := opq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := opq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderpercent.FieldID)
		for i := range fields {
			if fields[i] != orderpercent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := opq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := opq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := opq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := opq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (opq *OrderPercentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(opq.driver.Dialect())
	t1 := builder.Table(orderpercent.Table)
	columns := opq.fields
	if len(columns) == 0 {
		columns = orderpercent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if opq.sql != nil {
		selector = opq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if opq.unique != nil && *opq.unique {
		selector.Distinct()
	}
	for _, m := range opq.modifiers {
		m(selector)
	}
	for _, p := range opq.predicates {
		p(selector)
	}
	for _, p := range opq.order {
		p(selector)
	}
	if offset := opq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := opq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (opq *OrderPercentQuery) ForUpdate(opts ...sql.LockOption) *OrderPercentQuery {
	if opq.driver.Dialect() == dialect.Postgres {
		opq.Unique(false)
	}
	opq.modifiers = append(opq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return opq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (opq *OrderPercentQuery) ForShare(opts ...sql.LockOption) *OrderPercentQuery {
	if opq.driver.Dialect() == dialect.Postgres {
		opq.Unique(false)
	}
	opq.modifiers = append(opq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return opq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (opq *OrderPercentQuery) Modify(modifiers ...func(s *sql.Selector)) *OrderPercentSelect {
	opq.modifiers = append(opq.modifiers, modifiers...)
	return opq.Select()
}

// OrderPercentGroupBy is the group-by builder for OrderPercent entities.
type OrderPercentGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (opgb *OrderPercentGroupBy) Aggregate(fns ...AggregateFunc) *OrderPercentGroupBy {
	opgb.fns = append(opgb.fns, fns...)
	return opgb
}

// Scan applies the group-by query and scans the result into the given value.
func (opgb *OrderPercentGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := opgb.path(ctx)
	if err != nil {
		return err
	}
	opgb.sql = query
	return opgb.sqlScan(ctx, v)
}

func (opgb *OrderPercentGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range opgb.fields {
		if !orderpercent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := opgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := opgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (opgb *OrderPercentGroupBy) sqlQuery() *sql.Selector {
	selector := opgb.sql.Select()
	aggregation := make([]string, 0, len(opgb.fns))
	for _, fn := range opgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(opgb.fields)+len(opgb.fns))
		for _, f := range opgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(opgb.fields...)...)
}

// OrderPercentSelect is the builder for selecting fields of OrderPercent entities.
type OrderPercentSelect struct {
	*OrderPercentQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ops *OrderPercentSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ops.prepareQuery(ctx); err != nil {
		return err
	}
	ops.sql = ops.OrderPercentQuery.sqlQuery(ctx)
	return ops.sqlScan(ctx, v)
}

func (ops *OrderPercentSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ops.sql.Query()
	if err := ops.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ops *OrderPercentSelect) Modify(modifiers ...func(s *sql.Selector)) *OrderPercentSelect {
	ops.modifiers = append(ops.modifiers, modifiers...)
	return ops
}
