// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/inspire-manager/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/inspire-manager/pkg/db/ent/registration"
	"github.com/google/uuid"
)

// RegistrationUpdate is the builder for updating Registration entities.
type RegistrationUpdate struct {
	config
	hooks     []Hook
	mutation  *RegistrationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RegistrationUpdate builder.
func (ru *RegistrationUpdate) Where(ps ...predicate.Registration) *RegistrationUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetCreatedAt sets the "created_at" field.
func (ru *RegistrationUpdate) SetCreatedAt(u uint32) *RegistrationUpdate {
	ru.mutation.ResetCreatedAt()
	ru.mutation.SetCreatedAt(u)
	return ru
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ru *RegistrationUpdate) SetNillableCreatedAt(u *uint32) *RegistrationUpdate {
	if u != nil {
		ru.SetCreatedAt(*u)
	}
	return ru
}

// AddCreatedAt adds u to the "created_at" field.
func (ru *RegistrationUpdate) AddCreatedAt(u int32) *RegistrationUpdate {
	ru.mutation.AddCreatedAt(u)
	return ru
}

// SetUpdatedAt sets the "updated_at" field.
func (ru *RegistrationUpdate) SetUpdatedAt(u uint32) *RegistrationUpdate {
	ru.mutation.ResetUpdatedAt()
	ru.mutation.SetUpdatedAt(u)
	return ru
}

// AddUpdatedAt adds u to the "updated_at" field.
func (ru *RegistrationUpdate) AddUpdatedAt(u int32) *RegistrationUpdate {
	ru.mutation.AddUpdatedAt(u)
	return ru
}

// SetDeletedAt sets the "deleted_at" field.
func (ru *RegistrationUpdate) SetDeletedAt(u uint32) *RegistrationUpdate {
	ru.mutation.ResetDeletedAt()
	ru.mutation.SetDeletedAt(u)
	return ru
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ru *RegistrationUpdate) SetNillableDeletedAt(u *uint32) *RegistrationUpdate {
	if u != nil {
		ru.SetDeletedAt(*u)
	}
	return ru
}

// AddDeletedAt adds u to the "deleted_at" field.
func (ru *RegistrationUpdate) AddDeletedAt(u int32) *RegistrationUpdate {
	ru.mutation.AddDeletedAt(u)
	return ru
}

// SetAppID sets the "app_id" field.
func (ru *RegistrationUpdate) SetAppID(u uuid.UUID) *RegistrationUpdate {
	ru.mutation.SetAppID(u)
	return ru
}

// SetInviterID sets the "inviter_id" field.
func (ru *RegistrationUpdate) SetInviterID(u uuid.UUID) *RegistrationUpdate {
	ru.mutation.SetInviterID(u)
	return ru
}

// SetInviteeID sets the "invitee_id" field.
func (ru *RegistrationUpdate) SetInviteeID(u uuid.UUID) *RegistrationUpdate {
	ru.mutation.SetInviteeID(u)
	return ru
}

// Mutation returns the RegistrationMutation object of the builder.
func (ru *RegistrationUpdate) Mutation() *RegistrationMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RegistrationUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if err := ru.defaults(); err != nil {
		return 0, err
	}
	if len(ru.hooks) == 0 {
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RegistrationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			if ru.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RegistrationUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RegistrationUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RegistrationUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ru *RegistrationUpdate) defaults() error {
	if _, ok := ru.mutation.UpdatedAt(); !ok {
		if registration.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized registration.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := registration.UpdateDefaultUpdatedAt()
		ru.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ru *RegistrationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RegistrationUpdate {
	ru.modifiers = append(ru.modifiers, modifiers...)
	return ru
}

func (ru *RegistrationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   registration.Table,
			Columns: registration.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: registration.FieldID,
			},
		},
	}
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: registration.FieldCreatedAt,
		})
	}
	if value, ok := ru.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: registration.FieldCreatedAt,
		})
	}
	if value, ok := ru.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: registration.FieldUpdatedAt,
		})
	}
	if value, ok := ru.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: registration.FieldUpdatedAt,
		})
	}
	if value, ok := ru.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: registration.FieldDeletedAt,
		})
	}
	if value, ok := ru.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: registration.FieldDeletedAt,
		})
	}
	if value, ok := ru.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: registration.FieldAppID,
		})
	}
	if value, ok := ru.mutation.InviterID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: registration.FieldInviterID,
		})
	}
	if value, ok := ru.mutation.InviteeID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: registration.FieldInviteeID,
		})
	}
	_spec.Modifiers = ru.modifiers
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{registration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// RegistrationUpdateOne is the builder for updating a single Registration entity.
type RegistrationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RegistrationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedAt sets the "created_at" field.
func (ruo *RegistrationUpdateOne) SetCreatedAt(u uint32) *RegistrationUpdateOne {
	ruo.mutation.ResetCreatedAt()
	ruo.mutation.SetCreatedAt(u)
	return ruo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ruo *RegistrationUpdateOne) SetNillableCreatedAt(u *uint32) *RegistrationUpdateOne {
	if u != nil {
		ruo.SetCreatedAt(*u)
	}
	return ruo
}

// AddCreatedAt adds u to the "created_at" field.
func (ruo *RegistrationUpdateOne) AddCreatedAt(u int32) *RegistrationUpdateOne {
	ruo.mutation.AddCreatedAt(u)
	return ruo
}

// SetUpdatedAt sets the "updated_at" field.
func (ruo *RegistrationUpdateOne) SetUpdatedAt(u uint32) *RegistrationUpdateOne {
	ruo.mutation.ResetUpdatedAt()
	ruo.mutation.SetUpdatedAt(u)
	return ruo
}

// AddUpdatedAt adds u to the "updated_at" field.
func (ruo *RegistrationUpdateOne) AddUpdatedAt(u int32) *RegistrationUpdateOne {
	ruo.mutation.AddUpdatedAt(u)
	return ruo
}

// SetDeletedAt sets the "deleted_at" field.
func (ruo *RegistrationUpdateOne) SetDeletedAt(u uint32) *RegistrationUpdateOne {
	ruo.mutation.ResetDeletedAt()
	ruo.mutation.SetDeletedAt(u)
	return ruo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ruo *RegistrationUpdateOne) SetNillableDeletedAt(u *uint32) *RegistrationUpdateOne {
	if u != nil {
		ruo.SetDeletedAt(*u)
	}
	return ruo
}

// AddDeletedAt adds u to the "deleted_at" field.
func (ruo *RegistrationUpdateOne) AddDeletedAt(u int32) *RegistrationUpdateOne {
	ruo.mutation.AddDeletedAt(u)
	return ruo
}

// SetAppID sets the "app_id" field.
func (ruo *RegistrationUpdateOne) SetAppID(u uuid.UUID) *RegistrationUpdateOne {
	ruo.mutation.SetAppID(u)
	return ruo
}

// SetInviterID sets the "inviter_id" field.
func (ruo *RegistrationUpdateOne) SetInviterID(u uuid.UUID) *RegistrationUpdateOne {
	ruo.mutation.SetInviterID(u)
	return ruo
}

// SetInviteeID sets the "invitee_id" field.
func (ruo *RegistrationUpdateOne) SetInviteeID(u uuid.UUID) *RegistrationUpdateOne {
	ruo.mutation.SetInviteeID(u)
	return ruo
}

// Mutation returns the RegistrationMutation object of the builder.
func (ruo *RegistrationUpdateOne) Mutation() *RegistrationMutation {
	return ruo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RegistrationUpdateOne) Select(field string, fields ...string) *RegistrationUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Registration entity.
func (ruo *RegistrationUpdateOne) Save(ctx context.Context) (*Registration, error) {
	var (
		err  error
		node *Registration
	)
	if err := ruo.defaults(); err != nil {
		return nil, err
	}
	if len(ruo.hooks) == 0 {
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RegistrationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			if ruo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ruo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ruo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Registration)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from RegistrationMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RegistrationUpdateOne) SaveX(ctx context.Context) *Registration {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RegistrationUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RegistrationUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ruo *RegistrationUpdateOne) defaults() error {
	if _, ok := ruo.mutation.UpdatedAt(); !ok {
		if registration.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized registration.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := registration.UpdateDefaultUpdatedAt()
		ruo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ruo *RegistrationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RegistrationUpdateOne {
	ruo.modifiers = append(ruo.modifiers, modifiers...)
	return ruo
}

func (ruo *RegistrationUpdateOne) sqlSave(ctx context.Context) (_node *Registration, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   registration.Table,
			Columns: registration.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: registration.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Registration.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, registration.FieldID)
		for _, f := range fields {
			if !registration.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != registration.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: registration.FieldCreatedAt,
		})
	}
	if value, ok := ruo.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: registration.FieldCreatedAt,
		})
	}
	if value, ok := ruo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: registration.FieldUpdatedAt,
		})
	}
	if value, ok := ruo.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: registration.FieldUpdatedAt,
		})
	}
	if value, ok := ruo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: registration.FieldDeletedAt,
		})
	}
	if value, ok := ruo.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: registration.FieldDeletedAt,
		})
	}
	if value, ok := ruo.mutation.AppID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: registration.FieldAppID,
		})
	}
	if value, ok := ruo.mutation.InviterID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: registration.FieldInviterID,
		})
	}
	if value, ok := ruo.mutation.InviteeID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: registration.FieldInviteeID,
		})
	}
	_spec.Modifiers = ruo.modifiers
	_node = &Registration{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{registration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
