// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CouponAllocated is the predicate function for couponallocated builders.
type CouponAllocated func(*sql.Selector)

// CouponDiscount is the predicate function for coupondiscount builders.
type CouponDiscount func(*sql.Selector)

// CouponFixAmount is the predicate function for couponfixamount builders.
type CouponFixAmount func(*sql.Selector)

// CouponSpecialOffer is the predicate function for couponspecialoffer builders.
type CouponSpecialOffer func(*sql.Selector)
